### ISSUE TITLE
[TODO] FacebookURL settings

### ISSUE THREAD

**Issue by samuelgrant** [samuelgrant/fight-for-kidz#251]
Currently the facebook URL is stored in the .env file. 

This is a problem as the site admins do not know how to update this value.  We should move this setting into the database table `site_settings` and add a user interface for it on the admin dashboard page.

**Comment by samuelgrant** [comment]
cc @jacksos101

**Comment by samuelgrant** [comment]
Steps:

1. [ ] Add optional string to database `facebook_url`
2. [ ] IF facebook URL does not exist
    - Hide the widget on the home page
    - Add a banner on all admin pages with a link to the fix-it page
3. [ ] Add an admin site settings page/modal with an HTML input `type=url`
